export default [
  {
    id: 1,
    title: "Canvas Painting Workshop",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCA4IEp1bg%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00429374-fepuwgjkxe-portrait.jpg",
    year: "June 8, 2025",
    languages: "Ahmedabad",
    tags: ["Painting", "Canvas", "Art"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 799 }],
    description:
      "Explore your creativity with our Canvas Painting Workshop at 3AM Art House. Suitable for all skill levels.",
    date: "June 8, 2025",
    location: "3AM Art House, Ahmedabad",
  },
  {
    id: 2,
    title: "Make Your Own Magnet",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-V2VkLCA0IEp1biBvbndhcmRz,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00428700-caukkkxecx-portrait.jpg",
    year: "June 15, 2025",
    languages: "Ahmedabad",
    tags: ["Craft", "DIY", "Magnet"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 499 }],
    description:
      "Join us at Crazy Plant Lady Cafe to create your personalized magnets in this fun-filled workshop.",
    date: "June 15, 2025",
    location: "Crazy Plant Lady Cafe, Ahmedabad",
  },
  {
    id: 3,
    title: "Palette Knife Painting Workshop",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCA4IEp1bg%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00429378-hgmyaqgmcd-portrait.jpg",
    year: "June 22, 2025",
    languages: "Ahmedabad",
    tags: ["Painting", "Palette Knife", "Art"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 1099 }],
    description:
      "Discover the techniques of palette knife painting at 3AM Art House. Materials provided.",
    date: "June 22, 2025",
    location: "3AM Art House, Ahmedabad",
  },
  {
    id: 4,
    title: "Lippan Art",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCA3IEp1biBvbndhcmRz,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00441436-ysdjlejqmd-portrait.jpg",
    year: "June 29, 2025",
    languages: "Ahmedabad",
    tags: ["Lippan", "Mud Art", "Traditional"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 899 }],
    description:
      "Experience the traditional Lippan art form at Monkey Cafe. Create your own masterpiece.",
    date: "June 29, 2025",
    location: "Monkey Cafe, Ahmedabad",
  },
  {
    id: 5,
    title: "Fluid Art Workshop",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCA3IEp1biBvbndhcmRz,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00444022-kanuxazwyh-portrait.jpg",
    year: "July 6, 2025",
    languages: "Ahmedabad",
    tags: ["Fluid Art", "Abstract", "Painting"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 799 }],
    description:
      "Dive into the world of fluid art at Monkey Cafe. No prior experience needed.",
    date: "July 6, 2025",
    location: "Monkey Cafe, Ahmedabad",
  },
  {
    id: 6,
    title: "Tissue Texture Art",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCA3IEp1biBvbndhcmRz,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00445267-ahlxzjnaue-portrait.jpg",
    year: "July 13, 2025",
    languages: "Ahmedabad",
    tags: ["Texture", "Tissue", "Art"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 799 }],
    description:
      "Learn the art of creating textures using tissue paper at Monkey Cafe. Materials included.",
    date: "July 13, 2025",
    location: "Monkey Cafe, Ahmedabad",
  },
  {
    id: 7,
    title: "Dot Mandala Art",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCA3IEp1biBvbndhcmRz,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00444014-ptxehgjkge-portrait.jpg",
    year: "July 20, 2025",
    languages: "Ahmedabad",
    tags: ["Mandala", "Dot Art", "Painting"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 799 }],
    description:
      "Create intricate dot mandala designs in this calming workshop at Monkey Cafe.",
    date: "July 20, 2025",
    location: "Monkey Cafe, Ahmedabad",
  },
  {
    id: 8,
    title: "Knife Texture Art",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCA3IEp1biBvbndhcmRz,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00442127-ucfwedglkk-portrait.jpg",
    year: "July 27, 2025",
    languages: "Ahmedabad",
    tags: ["Texture", "Knife", "Art"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 799 }],
    description:
      "Explore knife texture techniques in this hands-on workshop at Monkey Cafe.",
    date: "July 27, 2025",
    location: "Monkey Cafe, Ahmedabad",
  },
  {
    id: 9,
    title: "ToteBag Painting",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCA3IEp1biBvbndhcmRz,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00444027-bkhawfmzkz-portrait.jpg",
    year: "August 3, 2025",
    languages: "Ahmedabad",
    tags: ["Painting", "ToteBag", "DIY"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 799 }],
    description:
      "Design and paint your own tote bag in this creative workshop at Monkey Cafe.",
    date: "August 3, 2025",
    location: "Monkey Cafe, Ahmedabad",
  },
];