export default [
  {
    id: 1,
    title: "Tara Sitara Night ft. Gurdas Maan Live",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-RnJpLCAxMyBKdW4%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00447668-swxmefelcu-portrait.jpg",
    date: "June 13, 2025",
    languages: "Punjabi",
    tags: ["Live Music", "Punjabi", "Folk"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 10000 }],
    description: "Experience the legendary Gurdas Maan live in concert at Khubani, Andaz Delhi.",
    location: "Khubani, Andaz, Delhi"
  },
  {
    id: 2,
    title: "Room XO Presents Lil Pump",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCA4IEp1bg%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00445847-tpqnqhkmjt-portrait.jpg",
    date: "June 8, 2025",
    languages: "English",
    tags: ["Hip-Hop", "Rap", "International Artist"],
    ua: "18+",
    tickets: [{ type: "GENERAL", price: 1999 }],
    description: "Join international rap sensation Lil Pump live at Room XO, Gurugram.",
    location: "Room XO, Gurugram"
  },
  {
    id: 3,
    title: "Sagar Waali Qawwali - Bharat Tour 2025 (Delhi)",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCA4IEp1bg%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00433847-rkpnxqrdfe-portrait.jpg",
    date: "June 8, 2025",
    languages: "Hindi",
    tags: ["Qawwali", "Sufi", "Live Performance"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 999 }],
    description: "Experience the soulful Qawwali performance by Sagar Waali Qawwali as part of their Bharat Tour 2025.",
    location: "K D Jadhav Wrestling Stadium (IGI Indoor Stadium), Delhi"
  },
  {
    id: 4,
    title: "Cap Mania Tour ft Himesh Reshammiya",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCAxOSBKdWw%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00441454-wlvzylljkn-portrait.jpg",
    date: "July 19, 2025",
    languages: "Hindi",
    tags: ["Bollywood", "Pop", "Live Concert"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 999 }],
    description: "Join Himesh Reshammiya live in concert as part of the Cap Mania Tour.",
    location: "Indira Gandhi Arena, Delhi"
  },
  {
    id: 5,
    title: "Qawaali by Nizami Bandhu",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCA4IEp1bg%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00418827-swgcnpbvkl-portrait.jpg",
    date: "June 8, 2025",
    languages: "Hindi",
    tags: ["Qawwali", "Sufi", "Traditional Music"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 399 }],
    description: "Enjoy an evening of traditional Qawwali music by the renowned Nizami Bandhu.",
    location: "Kamani Auditorium, Delhi"
  },
  {
    id: 6,
    title: "Swiftchella - A Taylor Swift-Themed Fan Party",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCA2IEp1bA%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00441036-ulxvezwwlu-portrait.jpg",
    date: "July 6, 2025",
    languages: "English",
    tags: ["Pop", "Fan Event", "Dance Party"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 499 }],
    description: "Celebrate the music of Taylor Swift at Swiftchella, a themed fan party.",
    location: "Shishi, Delhi"
  },
  {
    id: 7,
    title: "VILEN LIVE - DELHI",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-RnJpLCA0IEp1bA%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00441584-lfglqbyupn-portrait.jpg",
    date: "July 4, 2025",
    languages: "Hindi",
    tags: ["Indie", "Rock", "Live Performance"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 799 }],
    description: "Experience the electrifying performance of VILEN live in Delhi.",
    location: "Venue To Be Announced, Delhi NCR"
  },
  {
    id: 8,
    title: "Jazbaa Ft Rekha Bhardwaj Live in Concert",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCAyNyBKdWw%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00415475-pgyhyhssgh-portrait.jpg",
    date: "July 27, 2025",
    languages: "Hindi",
    tags: ["Sufi", "Ghazal", "Live Music"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 2999 }],
    description: "Join Rekha Bhardwaj for an evening of soulful Sufi and Ghazal music.",
    location: "Plenary Hall, Bharat Mandapam, Delhi"
  },
  {
    id: 9,
    title: "Mahesh Kale's Abhangwari - Delhi",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-RnJpLCAxMSBKdWw%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00441220-krxpmfnylw-portrait.jpg",
    date: "July 11, 2025",
    languages: "Marathi",
    tags: ["Classical", "Devotional", "Live Performance"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 599 }],
    description: "Experience the devotional Abhangs performed by Mahesh Kale in Delhi.",
    location: "Bharat Mandapam, Delhi"
  },
  {
    id: 10,
    title: "PokerBaazi Presents Nizami Brothers IGT Live",
    imageUrl: "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCAxNSBKdW4gb253YXJkcw%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00371174-fpjcfjkdvz-portrait.jpg",
    date: "June 15, 2025",
    languages: "Hindi",
    tags: ["Qawwali", "Sufi", "Live Performance"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 499 }],
    description: "Enjoy a live Qawwali performance by the Nizami Brothers, presented by PokerBaazi.",
    location: "Studio XO Bar, Sector 29, Gurugram"
  }
];