export default [
  {
    id: 1,
    title: "Humare Ram Ft Ashutosh Rana and Rahull R Bhuchar",
    imageUrl:
      "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCAyMiBKdW4%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00376688-mcvemzebsg-portrait.jpg",
    year: "June 22, 2025",
    languages: "Hindi",
    tags: ["Mythological", "Drama"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 799 }],
    description: "A grand theatrical experience...",
    date: "June 22, 2025",
    location: "Auda Auditorium, Shela, Ahmedabad",
  },
  {
    id: 2,
    title: "Chanakya - Hindi Play",
    imageUrl:
      "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCA4IEp1bg%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00097688-czqaxunuww-portrait.jpg",
    year: "June 8, 2025",
    languages: "Hindi",
    tags: ["Historical", "Drama"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 300 }],
    description: "A historical drama portraying Chanakya...",
    date: "June 8, 2025",
    location: "Thakorbhai Desai Hall, Ahmedabad",
  },
  {
    id: 3,
    title: "Welcome Zindagi - Ahmedabad",
    imageUrl:
      "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCAyMiBKdW4%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00376718-mmvjpqglcu-portrait.jpg",
    year: "June 22, 2025",
    languages: "Gujarati",
    tags: ["Drama", "Life"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 300 }],
    description: "A Gujarati play that delves into life's challenges...",
    date: "June 22, 2025",
    location: "Thakorbhai Desai Hall, Ahmedabad",
  },
  {
    id: 4,
    title: "OH WOMANIYA",
    imageUrl:
      "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCA4IEp1bg%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00433177-xesganhkwr-portrait.jpg",
    year: "June 8, 2025",
    languages: "Gujarati",
    tags: ["Comedy", "Women's Issues"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 250 }],
    description: "A Gujarati play focusing on women's issues...",
    date: "June 8, 2025",
    location: "HK Hall, Ahmedabad",
  },
  {
    id: 5,
    title: "Trumbak Tran Baydiwalo - Gujarat",
    imageUrl:
      "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCAyOSBKdW4%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00415371-gqbyxcubjs-portrait.jpg",
    year: "June 29, 2025",
    languages: "Gujarati",
    tags: ["Comedy", "Drama"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 250 }],
    description: "A Gujarati play showcasing regional stories...",
    date: "June 29, 2025",
    location: "Thakorbhai Desai Hall, Ahmedabad",
  },
  {
    id: 6,
    title: "Ankahee - A Silent Play",
    imageUrl:
      "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCA4IEp1bg%3D%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00443773-xansjtujlz-portrait.jpg",
    year: "June 8, 2025",
    languages: "Hindi",
    tags: ["Silent", "Experimental"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 250 }],
    description: "A unique silent play without dialogues...",
    date: "June 8, 2025",
    location: "Rhaen Basera, Ahmedabad",
  },
  {
    id: 7,
    title: "Tiku Piku Chiku",
    imageUrl:
      "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCA3IEp1biBvbndhcmRz,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00443124-fufcgfcekl-portrait.jpg",
    year: "June 7, 2025",
    languages: "Gujarati",
    tags: ["Children", "Comedy"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 250 }],
    description: "A fun children’s play in Gujarati...",
    date: "June 7, 2025",
    location: "Thakorbhai Desai Hall, Ahmedabad",
  },
  {
    id: 8,
    title: "Ajab Prem ni Gajab Kahani",
    imageUrl:
      "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U2F0LCAyMSBKdW4%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00447969-xwcpnhgedk-portrait.jpg",
    year: "June 21, 2025",
    languages: "Gujarati",
    tags: ["Romantic", "Comedy"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 300 }],
    description: "A romantic comedy in Gujarati...",
    date: "June 21, 2025",
    location: "Dinesh Hall, Ahmedabad",
  },
  {
    id: 9,
    title: "Gajab Thai Gayo!",
    imageUrl:
      "https://assets-in.bmscdn.com/discovery-catalog/events/tr:w-400,h-600,bg-CCCCCC:w-400.0,h-660.0,cm-pad_resize,bg-000000,fo-top:l-text,ie-U3VuLCAyMiBKdW4%3D,fs-29,co-FFFFFF,ly-612,lx-24,pa-8_0_0_0,l-end/et00446064-wycytvmdqy-portrait.jpg",
    year: "June 22, 2025",
    languages: "Gujarati",
    tags: ["Comedy", "Family"],
    ua: "All Ages",
    tickets: [{ type: "GENERAL", price: 350 }],
    description: "A hilarious family Gujarati play full of surprises.",
    date: "June 22, 2025",
    location: "HK College Hall, Ahmedabad",
  },
];
